### ISSUE TITLE
Heroku Deployment Issue

### ISSUE THREAD

**Issue by thekennysong** [beeman/loopback-angular-admin#86] opened 2015-06-19 15:03 UTC
Hello, 

First, I LOVE THIS! You did a really good job. When I deployed the app, I noticed some of the styles are messed up. You can check it out here, https://form-fun.herokuapp.com/

Thanks!

Kenny

**Comment by beeman** [comment] 2015-06-19 16:44
Hi @thekennysong , thanks a lot!

It should be fixed now, this was a duplicate of [this bug](https://github.com/beeman/loopback-angular-admin/issues/84#issuecomment-113570352)

**Closed by beeman** 2015-06-19 16:44 UTC
