### ISSUE TITLE
i am unable to run it.crashes with this error

### ISSUE THREAD

**Issue by approgramer** [beeman/loopback-angular-admin#146] opened 2015-11-17 20:08 UTC
loopback-angular-admin@0.1.1 start D:\la
> node server/server.js

(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DataSource.addListener (events.js:239:17)
    at DataSource.once (events.js:265:8)
    at DataSource.ready (D:\la\node_modules\loopback-datasource-juggler\lib\datasource.js:2037:8)
    at stillConnecting (D:\la\node_modules\loopback-datasource-juggler\lib\dao.js:363:18)
    at Function.DataAccessObject.create (D:\la\node_modules\loopback-datasource-juggler\lib\dao.js:159:27)
    at Function.Post.createFakeData (D:\la\common\models\post.js:6:17)
    at Object.module.exports [as func] (D:\la\server\boot\99-fake-data.js:34:39)
    at D:\la\node_modules\loopback-boot\lib\executor.js:253:9
    at iterate (D:\la\node_modules\async\lib\async.js:149:13)
    at D:\la\node_modules\async\lib\async.js:160:25
    at D:\la\node_modules\loopback-boot\lib\executor.js:255:7
    at iterate (D:\la\node_modules\async\lib\async.js:149:13)
    at D:\la\node_modules\async\lib\async.js:160:25
    at D:\la\node_modules\loopback-boot\lib\executor.js:255:7
    at iterate (D:\la\node_modules\async\lib\async.js:149:13)
    at D:\la\node_modules\async\lib\async.js:160:25
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DataSource.addListener (events.js:239:17)
    at DataSource.once (events.js:265:8)
    at DataSource.ready (D:\la\node_modules\loopback-datasource-juggler\lib\datasource.js:2038:8)
    at stillConnecting (D:\la\node_modules\loopback-datasource-juggler\lib\dao.js:363:18)
    at Function.DataAccessObject.create (D:\la\node_modules\loopback-datasource-juggler\lib\dao.js:159:27)
    at Function.Post.createFakeData (D:\la\common\models\post.js:6:17)
    at Object.module.exports [as func] (D:\la\server\boot\99-fake-data.js:34:39)
    at D:\la\node_modules\loopback-boot\lib\executor.js:253:9
    at iterate (D:\la\node_modules\async\lib\async.js:149:13)
    at D:\la\node_modules\async\lib\async.js:160:25
    at D:\la\node_modules\loopback-boot\lib\executor.js:255:7
    at iterate (D:\la\node_modules\async\lib\async.js:149:13)
    at D:\la\node_modules\async\lib\async.js:160:25
    at D:\la\node_modules\loopback-boot\lib\executor.js:255:7
    at iterate (D:\la\node_modules\async\lib\async.js:149:13)
    at D:\la\node_modules\async\lib\async.js:160:25
Please configure your passport strategy in `providers.json`.
Copy `providers.json.template` to `providers.json` and replace the clientID/clientSecret values with your own.
Running app in development mode
loopback-datasource-juggler deprecated Model hook "Post.beforeCreate" is deprecated, use Operation hooks instead. http://docs.strongloop.com/display/LB/Operation+hooks node_modules\lo
opback-datasource-juggler\lib\dao.js:270:9
Creating default settings
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:3000
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at Server._listen2 (D:\la\node_modules\loopback\node_modules\continuation-local-storage\node_modules\async-listener\index.js:72:23)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:452:9)
    at process._tickDomainCallback (node.js:399:17)
    at process.<anonymous> (D:\la\node_modules\loopback\node_modules\continuation-local-storage\node_modules\async-listener\index.js:19:15)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! loopback-angular-admin@0.1.1 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loopback-angular-admin@0.1.1 start script 'node server/server.js'.
npm ERR! This is most likely a problem with the loopback-angular-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls loopback-angular-admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\la\npm-debug.log

**Comment by denzelwamburu** [comment] 2016-01-15 11:47
@approgramer Seems like you didn't create a `provider.json` file. Create a new file `provider.json` then paste the contents of `providers.template.json` .

**Comment by beeman** [comment] 2016-01-30 00:54
Looking at this error it seems like the server was already running at that time: `Error: listen EADDRINUSE 0.0.0.0:3000`.

The EventEmitter error should be fixed. Please reopen this issue if the problem is still there.

**Closed by beeman** 2016-01-30 00:54 UTC

**Comment by wtlam** [comment] 2016-09-08 21:52
hi thanks in advance for help.

 i have the same error, and i made sure there is no services running at :3000 and i also copied over the provider.json 

error as following, just wondering who did you fix it? 


  boot:02-load-users Creating roles and users +0ms
  boot:03-load-content Creating categories and products +5ms
loopback deprecated loopback.cookieParser is deprecated. Use `require('cookie-parser');` instead. server/boot/passport.js:20:19
loopback deprecated loopback.session is deprecated. Use `require('express-session');` instead. server/boot/passport.js:21:37
Configuring passport
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DataSource.addListener (events.js:239:17)
    at DataSource.once (events.js:265:8)
    at DataSource.ready (/prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-datasource-juggler/lib/datasource.js:2110:8)
    at stillConnecting (/prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-datasource-juggler/lib/dao.js:367:23)
    at Function.DataAccessObject.create (/prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-datasource-juggler/lib/dao.js:160:27)
    at Object.module.exports [as func] (/prod6/alg/xbbl6ge/dev/web/loopbook/server/boot/passport.js:78:22)
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-boot/lib/executor.js:294:9
    at iterate (/prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/async/lib/async.js:146:13)
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/async/lib/async.js:157:25
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-boot/lib/executor.js:296:7
    at iterate (/prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/async/lib/async.js:146:13)
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/async/lib/async.js:157:25
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-boot/lib/executor.js:296:7
    at iterate (/prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/async/lib/async.js:146:13)
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/async/lib/async.js:157:25
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-boot/lib/executor.js:296:7
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DataSource.addListener (events.js:239:17)
    at DataSource.once (events.js:265:8)
    at DataSource.ready (/prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-datasource-juggler/lib/datasource.js:2111:8)
    at stillConnecting (/prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-datasource-juggler/lib/dao.js:367:23)
    at Function.DataAccessObject.create (/prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-datasource-juggler/lib/dao.js:160:27)
    at Object.module.exports [as func] (/prod6/alg/xbbl6ge/dev/web/loopbook/server/boot/passport.js:78:22)
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-boot/lib/executor.js:294:9
    at iterate (/prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/async/lib/async.js:146:13)
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/async/lib/async.js:157:25
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-boot/lib/executor.js:296:7
    at iterate (/prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/async/lib/async.js:146:13)
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/async/lib/async.js:157:25
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-boot/lib/executor.js:296:7
    at iterate (/prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/async/lib/async.js:146:13)
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/async/lib/async.js:157:25
    at /prod6/alg/xbbl6ge/dev/web/loopbook/node_modules/loopback-boot/lib/executor.js:296:7
  boot:99-fake.data Creating 15 items for model Post +519ms
  boot:99-fake.data Creating 15 items for model Event +18ms
  boot:99-fake.data Creating 15 items for model Note +23ms
  boot:99-fake.data Creating 15 items for model Page +11ms
Creating default settings
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:3000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickDomainCallback (node.js:400:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
