### ISSUE TITLE
Grunt dist issue

### ISSUE THREAD

**Issue by palmerjc** [beeman/loopback-angular-admin#103] opened 2015-08-06 13:31 UTC
It appears that the dist setup in the Gruntfile.js is missing something because the API does not come online.  Furthermore, it appears that there might be a minification issue that is preventing modules from loading as well.  Has anybody got a clean Gruntfile where the application loads without issue?

**Comment by palmerjc** [comment] 2015-08-06 13:35
![dist-app-loading-error](https://cloud.githubusercontent.com/assets/13563242/9112740/70935a92-3c1e-11e5-94bb-a7e4886b000c.png)

**Comment by brainwatch** [comment] 2015-08-29 20:25
Same here. Any fix ?

**Comment by beeman** [comment] 2016-03-30 18:23
What I notice from the screenshot is that it's trying to reach the api at port 9000 instead of 3000. Not sure if that's what's causing the issue.

I'm closing this for now, please reopen the issue with steps to reproduce if the issue is still relevant.

**Closed by beeman** 2016-03-30 18:23 UTC
